dwfl_get_debuginfod_client: add dummy parameter for --disable-libdebuginfod
Since the stub version of "dwfl_get_debuginfod_client" doesn't name its
parameter, building elfuitls fails on a system with gcc 10.2.1:

-----------------------------------------------------------------------------
$ ./configure ... --disable-libdebuginfod
$ make
  Making all in libdwfl
    CC       debuginfod-client.o
  /src/libdwfl/debuginfod-client.c: In function 'dwfl_get_debuginfod_client':
  /src/libdwfl/debuginfod-client.c:145:29: error: parameter name omitted
    145 | dwfl_get_debuginfod_client (Dwfl *)
        |                             ^~~~~~
  make[2]: *** [Makefile:707: debuginfod-client.o] Error 1
-----------------------------------------------------------------------------

This fixes the issue by providing a name for the unused parameter.

Signed-off-by: Shahab Vahedi <shahab@synopsys.com>