debuginfod: Remove unused variable
Recent commit acd9525e9 has removed all references to max_fds
therefore remove it, moreover clang18 is happier

| ../../elfutils-0.191/debuginfod/debuginfod.cxx:1448:8: error: private field 'max_fds' is not used [-Werror,-Wunused-private-field]
|  1448 |   long max_fds;
|       |        ^
| 1 error generated.

Signed-off-by: Khem Raj <raj.khem@gmail.com>